word_list = []
word_list.append(input("Type in a place"))
word_list.append(input("Type in a adjective"))
word_list.append(input("Type in a place"))
word_list.append(input("Type in a person"))
word_list.append(input("Type in a subject"))
word_list.append(input("Type in a subject"))
word_list.append(input("Type in a sport ending with 'ing' "))
word_list.append(input("Type in a verb"))
word_list.append(input("Type in a place"))
word_list.append(input("Type in a place"))

print("Today i went %s" % word_list[0])
print("It was very %s" % word_list[1])
print("Then we went to %s" % word_list[2])
print("After, we met a man named %s" % word_list[3])
print("He told us about %s" % word_list[4])
print("Then he told us %s jokes" % word_list[5])
print("I was %s" % word_list[6])
print("Then we went %s" % word_list[7])
print("And before we left, i went to %s" % word_list[8])
print("We left to my %s" % word_list[9])
