verb1 = input("Type in a verb': ")
adjective = input("Type in a adjective': ")
noun1 = input("Type in this noun': ")
noun2 = input("Type in this noun': ")
noun3 = input("Type in this noun': ")
noun4 = input("Type in this noun': ")
verb2 = input("Type in a verb': ")
verb3 = input("Type in a verb': ")
adjective2 = input("Type in a adjective': ")
adjective3 = input("Type in a adjective': ")

print("Today i went %s" % verb1)
print("It was very %s" % adjective)
print("Then we went to %s" % noun1)
print("After, we met a man named %s" % noun2)
print("He told us about %s" % noun3)
print("Then he told us %s jokes" % adjective2)
print("I was %s" % adjective3)
print("Then we went %s" % verb2)
print("And before we left i went %s" % verb3)
print("We left to my %s" % noun4)

